# Generated by Django 2.1.7 on 2019-06-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='in_cart',
            field=models.IntegerField(default=0),
        ),
    ]
