# Generated by Django 2.1.7 on 2019-06-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_person_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Person'),
        ),
    ]
