# Generated by Django 2.1.7 on 2019-06-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_item_pers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pers',
        ),
        migrations.AddField(
            model_name='item',
            name='pers',
            field=models.ManyToManyField(to='ecom.Person'),
        ),
    ]
