# Generated by Django 2.1.7 on 2019-06-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20190602_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pers',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(to='ecom.Item'),
        ),
    ]
