# Generated by Django 2.1.7 on 2019-06-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20190602_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
